site_name: 'Jetstream2 Wiki'
site_url: https://wiki.jetstream-cloud.org
site_description: "Jetstream 2 Wiki"
repo_url: https://github.com/jetstream-cloud/Jetstream2Wiki

theme: "readthedocs"

google_analytics: ['UA-204881722-1','wiki.jetstream-cloud.org']
#https://github.com/mkdocs/mkdocs/issues/2101
#https://github.com/mkdocs/mkdocs/issues/1794

#extra:
#  analytics:
#    provider: google
#    property: 'UA-204881722-1'
#  consent:
#    title: Cookie consent
#    description: > 
#      We use cookies to recognize your repeated visits and preferences, as well
#      as to measure the effectiveness of our documentation and whether users
#      find what they're searching for. With your consent, you're helping us to
#      make our documentation better.
   

nav:
  - Overview: index.md
  - Key Differences: KeyDifferences.md
  - Migrating from Jetstream1 to Jetstream2: migrating.md
  - Key Features of Jetstream2: keyf.md
  - Configuration and specifications: config.md
  - Network configuration and considerations: network.md
  - Frequently Asked Questions:
    - Troubleshooting: faq/trouble.md
    - Allocations: faq/alloc.md
    - Security: faq/security.md
    - Software: faq/software.md
  - General Usage Information:
    - Featured Images: general/featured.md
    - Jetstream2 Software Collection: general/software.md
    - Software Licenses: general/licenses.md
    - XSEDE Service Units and Jetstream2: general/xsede.md
    - Jetstream2 Resources: general/resources.md
    - VM Sizes and Configurations: general/vmsizes.md
    - Policies and Best Practices:
      - Acceptable Usage Policies: general/policies.md
      - Export Control Guidance: general/export.md
      - AUPs for Jetstream2 Hosted Gateways: general/gateways.md
  - Allocations:
    - Trial allocation: alloc/trial.md
  - User Interfaces:
    - Atmosphere: ui/atmo.md
    - Exosphere: ui/exo.md
    - Horizon: ui/hrzn.md
    - CLI: ui/cli.md
  - General VM Operations:
    - Firewalls: general/firewalls.md
    - Manila: general/manila.md
    - File Transfer: general/filetransfer.md
    - Add User to a VM: general/adduser.md
    - Installing Software on your VM: general/installsoftware.md
    - Jupyter on Jetstream2: general/jupyter.md
    - Containers on Jetstream2: general/containers.md
    - Terraform on Jetstream2: general/terraform.md
    - Virtual Clusters on Jetstream2: general/virtualclusters.md
    - Galaxy: general/galaxy.md
